<?php

class Map {

	public static $map =
		array(
	    '/' => 'main.xml',
	    'books' => 'books/search.xml',
	    'register' => 'register/index.xml',
	    'emailconfirm/%d/%s' => 'misc/email_confirm.xml',
	    'backend/*' => 'admin/admin.xml',
	    404 => 'errors/p404.xml',
	    502 => 'errors/p502.xml',
	    'book/%d' => 'books/book.xml',
	    'me' => 'me/me.xml',
	    'search' => 'search/index.xml',
	    'user/%s' => 'users/user.xml',
	    'user/%s/edit' => 'users/edit.xml',
	    'user/%s/books' => 'users/shelves.xml',
	    'user/%s/books/%s' => 'users/shelf.xml',
	    'user/%s/friends' => 'users/friends.xml',
	    'user/%s/followers' => 'users/friends.xml',
	    'user/%s/wall' => 'users/wall.xml',
	    'user/%s/wall/%d' => 'users/wall.xml',
	    'user/%s/contact' => 'me/messages.xml',
	    'user/%s/reviews' => 'users/reviews.xml',
	    'author/%d' => 'authors/author.xml',
	    'user/%s/log' => 'users/log.xml',
	    'user/%s/wall/%d' => 'users/wallitem.xml',
	    'authors' => 'authors/news.xml',
	    'new' => 'books/news.xml',
	    'popular' => 'books/popular.xml',
	    'book/%d/edit' => 'books/edit.xml',
	    'book/%d/download' => 'books/download.xml',
	    'download/%d/%s' => 'download.xml',
	    'book/%d/relations' => 'books/relations.xml',
	    'genres/%s' => 'genres/genre.xml',
	    'genres/%d' => 'genres/genre.xml',
	    'genres/%d/edit' => 'genres/edit.xml',
	    'author/%d/edit' => 'authors/edit.xml',
	    'book/new' => 'books/new.xml',
	    'author/new' => 'authors/new.xml',
	    'a/%d/bibliography' => 'authors/bibliography.xml',
	    'me/wall' => 'me/wall.xml',
	    'me/wall/self' => 'me/wall_self.xml',
	    'me/wall/post' => 'me/wallpost.xml',
	    'series' => 'series/index.xml',
	    'series/%d' => 'series/serie.xml',
	    'series/new' => 'series/new.xml',
	    'series/%d/log' => 'series/log.xml',
	    'm' => 'magazines/index.xml',
	    'm/%d' => 'magazines/magazine.xml',
	    'forum' => 'forum/forum.xml',
	    'series/%d/edit' => 'series/edit.xml',
	    'genres' => 'genres/index.xml',
	    'forum/%d' => 'forum/themes.xml',
	    'forum/%d/%d' => 'forum/theme.xml',
	    'me/messages' => 'me/messages.xml',
	    'me/messages/%d' => 'me/messages_thread.xml',
	    'book/%d/log' => 'books/log.xml',
	    'author/%d/log' => 'authors/log.xml',
	    'log' => 'log/index.xml',
	    'tracker' => 'tracker/index.xml',
	    'magazine/%d/edit' => 'magazines/edit.xml',
	    'm/%d/log' => 'magazines/log.xml',
	);
	public static $sinonim =
		array(
	    'g/%d' => 'genres/%d',
	    'user/%d' => 'user/%s',
	    'user/%d/edit' => 'user/%d/edit',
	    'user/%d/books' => 'user/%s/books',
	    'user/%d/books/%s' => 'user/%s/books/%s',
	    'user/%d/friends' => 'user/%s/friends',
	    'user/%d/followers' => 'user/%s/followers',
	    'user/%d/wall' => 'user/%s/wall',
	    'user/%d/wall/%d' => 'user/%s/wall/%d',
	    'user/%d/reviews' => 'user/%s/reviews',
	    'user/%d/contact' => 'user/%s/contact',
	    'b/%d' => 'book/%d',
	    'a/%d/log' => 'author/%d/log',
	    'b/%d/edit' => 'book/%d/edit',
	    'a/%d/edit' => 'author/%d/edit',
	    'a/new' => 'author/new',
	    's/%d/log' => 'series/%d/log',
	    'b/new' => 'book/new',
	    'a/%d' => 'author/%d',
	    's/%d' => 'series/%d',
	    'magazines' => 'm',
	    'magazine/%d' => 'm/%d',
	    'magazine/%d/log' => 'm/%d/log',
	    's/%d/edit' => 'series/%d/edit',
	    's/new' => 'series/new',
	    'b/%d/relations' => 'book/%d/relations',
	    'b/%d/log' => 'book/%d/log',
	    'post/%d' => 'user/%s/wall/%d',
	);

}
